checkshttp
adevinta/vulcan-checks pull request #760
Opened 2024-12-04 14:11 UTC by jesusfcr

- **Split ARG to allow skaffold manage them**
- **Remomve logger global variable**
- **Use new http sdk**
- **Update vulcan-check-sdk**
- **Allow aws checks to use existing credentials without assumerole**

2024-12-10 09:16 UTC, seilagamo requested changes

2024-12-10 09:16 UTC, seilagamo commented on cmd/vulcan-trivy/vulcan-trivy.go
> +	loggerr          = check.NewCheckLog(checkName)
Remove the global loggerr variable

2024-12-10 10:01 UTC, jesusfcr commented on cmd/vulcan-trivy/vulcan-trivy.go
> +	loggerr          = check.NewCheckLog(checkName)
Thanks!

2025-02-17 10:38 UTC, danfaizer requested changes
Hey @jesusfcr 
Thanks a lot for the tedious but necessary PR. Really appreciate it.

I've added some minor comments before approve.
Feel free to comment for further details/discussion.

2025-02-17 11:14 UTC, jesusfcr commented on cmd/vulcan-ipv6/main.go
>  	checkName = "vulcan-ipv6"
thanks, done

2025-02-17 11:14 UTC, jesusfcr commented on cmd/vulcan-govulncheck/main.go
> +	repoPath, _, err := helpers.CloneGitRepositoryContext(ctx, target, opt.Branch, opt.Depth)
done in 5af94dc

2025-02-17 11:15 UTC, jesusfcr commented on cmd/vulcan-gitleaks/main.go
> +	repoPath, branch, err := helpers.CloneGitRepositoryContext(ctx, target, opt.Branch, opt.Depth)
Right, also I simplified it 7af7d5d

2025-02-17 12:24 UTC, danfaizer approved these changes
👍

2025-02-17 12:35 UTC, seilagamo approved these changes
LGTM

2025-02-17 12:42 UTC, merged